apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: activemq
  application: activemq
spec:
  adminPassword: admin
  adminUser: admin
  console:
    expose: true
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    clustered: true
    messageMigration: false
    persistenceEnabled: true
    requireLogin: false
    size: 1
    storage:
      size: 5Gi
